mysql:
  host: uzsk
  port: uzsk
  database: uzsk
  username: uzsk
  password: uzsk

experience:
  # ネットワーク最終ログインから1日以上経っていたら
  on_login_network:
    increase_parcentage: 50.0
  # ブロックを破壊したとき
  on_break_block: 
    increase_parcentage: 5.0
  # ブロックを設置したとき
  on_place_block:
    increase_parcentage: 5.0
  # モブを倒したとき
  on_kill_mob:
    increase_parcentage: 5.0
  # チャットを送信したとき
  on_chat:
    increase_parcentage: 5.0

sidebar:
  enabled: true
  title: "&dウズシカさーばー"
  lines:
    - "&rServer: "
    - "&r接続数: {ONLINE_PLAYERS}"
    - "&rレベル: {LEVEL} ({EXP_PERCENTAGE}%)"
    - "&r{PING}ms"
    - "&r{WORLD}"
    - "&r{WORLD_TIME} ({WEATHER})"
    - "&r{X}, {Y}, {Z} ({DIRECTION})"
    - "&r{TPS}TPS"
    - "&r{USAGE_RAM} / {TOTAL_RAM} MB"
    - "&7{DATE} {TIME}"
  pattern:
    date: YY/MM/dd
    time: HH:mm:ss
    world_date: MM/dd
    world_time: HH:mm

bossbar:
  enabled: true
  bars:
    - name: "Level"
      content: "&r{LEVEL}Lv &r[{EXP_PROGRESS_BAR}&r] ({EXP_PERCENTAGE}%)"
      color: PINK
      overlay: PROGRESS
      progress: 0.5

webapi:
  endpoint_url: http://uszk_webapi:8080/api/