mysql:
  host: uzsk
  port: uzsk
  database: uzsk
  username: uzsk
  password: uzsk

experience:
  # ネットワーク最終ログインから1日以上経っていたら
  on_login_network:
    increase_parcentage: 50.0
  # ブロックを破壊したとき
  on_break_block: 
    increase_parcentage: 5.0
  # ブロックを設置したとき
  on_place_block:
    increase_parcentage: 5.0
  # モブを倒したとき
  on_kill_mob:
    increase_parcentage: 5.0
  # チャットを送信したとき
  on_chat:
    increase_parcentage: 5.0